export interface PersonalTask {
  id: string;
  title: string;
  description?: string;
  deadline?: string;
  url?: string;
  done: boolean;
  createdAt: string;
  applicationId?: string; // Link to source application
  autoGenerated?: boolean; // Mark as auto-generated task
}
