import { useState, useMemo, useCallback, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { Application } from '@/types/application';
import { useLocalApplications } from '@/hooks/useLocalApplications';
import { usePersonalTasks } from '@/hooks/usePersonalTasks';
import { useAutoSave } from '@/hooks/useAutoSave';
import { DashboardStats, ApplicationList } from '@/components/dashboard';
import { ApplicationCard } from '@/components/ApplicationCard';
import { ApplicationForm } from '@/components/ApplicationForm';
import { CoachingPanel } from '@/components/CoachingPanel';
import { IntelligentTools } from '@/components/IntelligentTools';
import { SmartImportModal } from '@/components/SmartImportModal';
import { CVGeneratorModal } from '@/components/CVGeneratorModal';
import { LetterGeneratorModal } from '@/components/LetterGeneratorModal';
import { WeekCalendarView } from '@/components/WeekCalendarView';
import { PersonalTaskManager } from '@/components/PersonalTaskManager';
import { ProductivityView } from '@/components/ProductivityView';
import { DataManager } from '@/components/DataManager';
import { FilterPanel, FilterState } from '@/components/FilterPanel';
import { DeadlineNotifications } from '@/components/DeadlineNotifications';
import { SupabaseMigration } from '@/components/SupabaseMigration';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog';
import { Plus, Search, Target, BarChart3, Briefcase, Calendar as CalendarIcon, CheckCircle, Zap, Database, Loader2, Trash2, Cloud } from 'lucide-react';
import { toast } from 'sonner';
import { sortByPriority, getPriorityScore } from '@/lib/priorityEngine';
import { COACHING_LIBRARY } from '@/data/coaching';
import { createDeadlineTask, createFollowUpTask, taskExists } from '@/lib/taskAutomation';

const Index = () => {
  const navigate = useNavigate();
  const { applications, loading, addApplication, updateApplication, deleteApplication, importApplications, refetch } = useLocalApplications();
  const { tasks: personalTasks, addTask: addPersonalTask, toggleTask: togglePersonalTask, deleteTask: deletePersonalTask, updateTask: updatePersonalTask } = usePersonalTasks();
  
  // Auto-save hook
  const { formattedLastSave, triggerSave } = useAutoSave({
    interval: 30000, // 30 secondes
    onSave: () => {
      // Les données sont déjà sauvegardées par les hooks individuels
      // Ce hook sert juste à tracker la dernière sauvegarde
    }
  });
  const [searchQuery, setSearchQuery] = useState('');
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [editingApplication, setEditingApplication] = useState<Application | undefined>();
  const [isEmailImportOpen, setIsEmailImportOpen] = useState(false);
  const [isDataManagerOpen, setIsDataManagerOpen] = useState(false);
  const [selectedApplicationForCV, setSelectedApplicationForCV] = useState<Application | null>(null);
  const [selectedApplicationForLetter, setSelectedApplicationForLetter] = useState<Application | null>(null);
  const [activeTab, setActiveTab] = useState<'dashboard' | 'offres' | 'candidatures' | 'archives' | 'calendrier' | 'taches' | 'productivite'>('dashboard');
  const [filters, setFilters] = useState<FilterState>({});

  // Track previous applications for detecting status changes
  const prevApplicationsRef = useRef<Application[]>([]);

  // TASK AUTOMATION: Auto-create tasks when applications are imported or status changes
  useEffect(() => {
    if (loading || applications.length === 0) return;
    
    const prevApps = prevApplicationsRef.current;
    
    // Check for newly imported applications with deadlines (create deadline task)
    applications.forEach(app => {
      const wasExisting = prevApps.find(p => p.id === app.id);
      
      // New application with deadline -> create "Envoyer candidature" task for J-1
      if (!wasExisting && app.deadline && !app.deadlineMissing) {
        const deadlineTask = createDeadlineTask(app);
        if (deadlineTask && !taskExists(personalTasks, deadlineTask.title)) {
          addPersonalTask({
            ...deadlineTask,
            applicationId: app.id,
            autoGenerated: true
          });
        }
      }
      
      // Status changed to 'soumise' -> create "Relance" task at J+7
      if (wasExisting && wasExisting.statut !== 'soumise' && app.statut === 'soumise') {
        const followUpTask = createFollowUpTask(app);
        if (!taskExists(personalTasks, followUpTask.title)) {
          addPersonalTask({
            ...followUpTask,
            applicationId: app.id,
            autoGenerated: true
          });
        }
      }
    });
    
    prevApplicationsRef.current = [...applications];
  }, [applications, loading, personalTasks, addPersonalTask]);

  // Reset all applications
  const handleResetAll = useCallback(async () => {
    localStorage.removeItem('sosoflow_applications');
    toast.success('🗑️ Toutes les données ont été supprimées');
    window.location.reload();
  }, []);

  // Memoized filter function
  const applyFilters = useCallback((apps: Application[]) => {
    return apps.filter(app => {
      if (filters.statut && app.statut !== filters.statut) return false;
      if (filters.prioriteMin !== undefined && app.priorite < filters.prioriteMin) return false;
      if (filters.prioriteMax !== undefined && app.priorite > filters.prioriteMax) return false;
      if (filters.dateDebut && app.deadline < filters.dateDebut) return false;
      if (filters.dateFin && app.deadline > filters.dateFin) return false;
      return true;
    });
  }, [filters]);

  // Memoized: Distinction entre offres, candidatures en cours, archives
  const { offres, candidaturesEnCours, archives } = useMemo(() => {
    // Offres disponibles: à compléter seulement (pas expirées, pas envoyées)
    const offresDisponibles = applications.filter(app => 
      (app.statut === 'à compléter') && 
      !app.isExpired
    );
    
    // En cours de travail: statut 'en cours' (pas encore envoyées)
    const enCours = applications.filter(app => app.statut === 'en cours');
    
    // Archives: expirées OU envoyées (soumise/entretien)
    const archivees = applications.filter(app => 
      app.isExpired || 
      app.statut === 'soumise' || 
      app.statut === 'entretien'
    );
    
    return {
      offres: offresDisponibles,
      candidaturesEnCours: enCours,
      archives: archivees
    };
  }, [applications]);

  // Memoized: Filtered lists
  const { filteredOffres, filteredCandidatures, filteredArchives } = useMemo(() => ({
    filteredOffres: applyFilters(offres),
    filteredCandidatures: applyFilters(candidaturesEnCours),
    filteredArchives: applyFilters(archives)
  }), [offres, candidaturesEnCours, archives, applyFilters]);

  // Memoized: Sorted applications for dashboard - DEADLINE PRIORITY
  // Order: 1) Applications with deadline (chronological ascending - closest first)
  //        2) Applications without deadline (by creation date descending)
  const sortedApplications = useMemo(() => {
    const filtered = applications.filter(app => 
      app.entreprise.toLowerCase().includes(searchQuery.toLowerCase()) ||
      app.poste.toLowerCase().includes(searchQuery.toLowerCase()) ||
      app.lieu.toLowerCase().includes(searchQuery.toLowerCase())
    );
    
    return [...filtered].sort((a, b) => {
      const now = new Date();
      const deadlineA = a.deadline ? new Date(a.deadline) : null;
      const deadlineB = b.deadline ? new Date(b.deadline) : null;
      
      // Both have deadlines: sort by deadline ascending (closest first)
      if (deadlineA && deadlineB) {
        return deadlineA.getTime() - deadlineB.getTime();
      }
      
      // Only A has deadline: A comes first
      if (deadlineA && !deadlineB) return -1;
      
      // Only B has deadline: B comes first
      if (!deadlineA && deadlineB) return 1;
      
      // Neither has deadline: sort by creation date descending (most recent first)
      return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
    });
  }, [applications, searchQuery]);

  // Memoized: Sorted offres list
  const sortedFilteredOffres = useMemo(() => {
    return filteredOffres
      .filter(app => 
        app.entreprise.toLowerCase().includes(searchQuery.toLowerCase()) ||
        app.poste.toLowerCase().includes(searchQuery.toLowerCase()) ||
        app.lieu.toLowerCase().includes(searchQuery.toLowerCase())
      )
      .sort((a, b) => {
        const scoreA = getPriorityScore(a);
        const scoreB = getPriorityScore(b);
        if (scoreB.total !== scoreA.total) return scoreB.total - scoreA.total;
        return b.priorite - a.priorite;
      });
  }, [filteredOffres, searchQuery]);

  // Memoized: Sorted candidatures list (en cours de travail)
  const sortedFilteredCandidatures = useMemo(() => {
    return filteredCandidatures
      .filter(app => 
        app.entreprise.toLowerCase().includes(searchQuery.toLowerCase()) ||
        app.poste.toLowerCase().includes(searchQuery.toLowerCase()) ||
        app.lieu.toLowerCase().includes(searchQuery.toLowerCase())
      )
      .sort((a, b) => {
        const scoreA = getPriorityScore(a);
        const scoreB = getPriorityScore(b);
        if (scoreB.total !== scoreA.total) return scoreB.total - scoreA.total;
        return b.priorite - a.priorite;
      });
  }, [filteredCandidatures, searchQuery]);

  // Memoized: Sorted archives list
  const sortedFilteredArchives = useMemo(() => {
    return filteredArchives
      .filter(app => 
        app.entreprise.toLowerCase().includes(searchQuery.toLowerCase()) ||
        app.poste.toLowerCase().includes(searchQuery.toLowerCase()) ||
        app.lieu.toLowerCase().includes(searchQuery.toLowerCase())
      )
      .sort((a, b) => {
        // Sort by creation date, newest first
        return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
      });
  }, [filteredArchives, searchQuery]);

  // useCallback: Handlers to prevent unnecessary re-renders
  const handleSave = useCallback(async (application: Application) => {
    if (editingApplication) {
      await updateApplication(application.id, application);
    } else {
      await addApplication(application);
    }
    setEditingApplication(undefined);
    setIsFormOpen(false);
  }, [editingApplication, updateApplication, addApplication]);

  const handleEdit = useCallback((application: Application) => {
    setEditingApplication(application);
    setIsFormOpen(true);
  }, []);

  const handleDelete = useCallback(async (id: string) => {
    await deleteApplication(id);
  }, [deleteApplication]);

  const handleNewApplication = useCallback(() => {
    setEditingApplication(undefined);
    setIsFormOpen(true);
  }, []);

  const handleImportJobs = useCallback(async (jobs: Partial<Application>[]): Promise<string[]> => {
    return await importApplications(jobs);
  }, [importApplications]);

  const handleImportData = useCallback(async (importedApps: Application[]) => {
    await importApplications(importedApps);
  }, [importApplications]);

  const handleSaveCV = useCallback(async (cvUrl: string) => {
    if (selectedApplicationForCV) {
      await updateApplication(selectedApplicationForCV.id, { url: cvUrl });
      toast.success('CV sauvegardé');
    }
    setSelectedApplicationForCV(null);
  }, [selectedApplicationForCV, updateApplication]);

  const handleSaveLetter = useCallback(async (lettreUrl: string) => {
    if (selectedApplicationForLetter) {
      await updateApplication(selectedApplicationForLetter.id, { url: lettreUrl });
      toast.success('Lettre sauvegardée');
    }
    setSelectedApplicationForLetter(null);
  }, [selectedApplicationForLetter, updateApplication]);

  const handleUpdateApplication = useCallback(async (id: string, updates: Partial<Application>) => {
    await updateApplication(id, updates);
  }, [updateApplication]);

  const handleGenerateCV = useCallback((application: Application) => {
    setSelectedApplicationForCV(application);
  }, []);

  const handleGenerateLetter = useCallback((application: Application) => {
    setSelectedApplicationForLetter(application);
  }, []);

  // Memoized tabs config
  const tabs = useMemo(() => [
    { id: 'dashboard' as const, label: 'Tableau de bord', icon: BarChart3 },
    { id: 'offres' as const, label: 'Offres disponibles', icon: Target, badge: filteredOffres.length },
    { id: 'candidatures' as const, label: 'En cours', icon: Briefcase, badge: filteredCandidatures.length },
    { id: 'archives' as const, label: 'Archives', icon: Database, badge: filteredArchives.length },
    { id: 'calendrier' as const, label: 'Calendrier', icon: CalendarIcon },
    { id: 'taches' as const, label: 'Tâches', icon: CheckCircle },
    { id: 'productivite' as const, label: 'Productivité', icon: Zap },
  ], [filteredOffres.length, filteredCandidatures.length, filteredArchives.length]);

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-background via-background to-secondary/20 flex items-center justify-center">
        <div className="text-center">
          <Loader2 className="w-12 h-12 animate-spin mx-auto mb-4 text-primary" />
          <p className="text-muted-foreground">Chargement...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background to-secondary/20">
      <SupabaseMigration />
      
      {/* Header */}
      <header className="border-b-2 bg-card/50 backdrop-blur-sm sticky top-0 z-10 shadow-sm">
        <div className="container mx-auto px-4 sm:px-6 py-4 sm:py-6">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-gradient-to-br from-primary to-accent shadow-md">
                <Target className="w-6 h-6 text-white" />
              </div>
              <div>
                <h1 className="text-xl sm:text-2xl font-bold bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
                  SoSoFlow
                </h1>
                <p className="text-xs sm:text-sm text-muted-foreground">Votre assistant carrière intelligent</p>
              </div>
            </div>
            
            <div className="flex flex-wrap items-center gap-2 w-full sm:w-auto">
              <DeadlineNotifications applications={applications} />
              
              {/* Reset All Button */}
              <AlertDialog>
                <AlertDialogTrigger asChild>
                  <Button 
                    variant="ghost" 
                    size="default"
                    className="gap-2 flex-1 sm:flex-none text-destructive hover:text-destructive hover:bg-destructive/10"
                  >
                    <Trash2 className="w-5 h-5" />
                    <span className="hidden sm:inline">Réinitialiser</span>
                  </Button>
                </AlertDialogTrigger>
                <AlertDialogContent>
                  <AlertDialogHeader>
                    <AlertDialogTitle>🗑️ Réinitialiser toutes les données ?</AlertDialogTitle>
                    <AlertDialogDescription>
                      Cette action est irréversible. Toutes vos offres et candidatures seront supprimées définitivement.
                    </AlertDialogDescription>
                  </AlertDialogHeader>
                  <AlertDialogFooter>
                    <AlertDialogCancel>Annuler</AlertDialogCancel>
                    <AlertDialogAction onClick={handleResetAll} className="bg-destructive text-destructive-foreground hover:bg-destructive/90">
                      Supprimer tout
                    </AlertDialogAction>
                  </AlertDialogFooter>
                </AlertDialogContent>
              </AlertDialog>
              
              <Button 
                variant="ghost" 
                size="default"
                onClick={() => setIsDataManagerOpen(true)}
                className="gap-2 flex-1 sm:flex-none"
              >
                <Cloud className="w-5 h-5" />
                <span className="hidden sm:inline">☁️ Sauvegarder</span>
              </Button>
              <Button 
                variant="outline" 
                size="default"
                onClick={() => setActiveTab('calendrier')}
                className="gap-2 flex-1 sm:flex-none"
              >
                <CalendarIcon className="w-5 h-5" />
                <span className="hidden sm:inline">Calendrier</span>
              </Button>
              <Button onClick={() => setIsEmailImportOpen(true)} size="default" className="gap-2 flex-1 sm:flex-none">
                <Plus className="w-5 h-5" />
                <span className="hidden sm:inline">Nouvelle offre</span>
              </Button>
            </div>
          </div>
        </div>
      </header>

      <main className="container mx-auto px-4 sm:px-6 py-6 sm:py-8">
        {/* Navigation Tabs */}
        <div className="flex flex-wrap gap-2 sm:gap-3 mb-6 sm:mb-8">
          {tabs.map(tab => {
            const Icon = tab.icon;
            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`min-h-[44px] px-4 sm:px-5 py-2.5 sm:py-3 rounded-lg flex items-center gap-2 transition-all duration-200 font-medium ${
                  activeTab === tab.id 
                    ? 'bg-primary text-primary-foreground shadow-lg scale-[1.02]' 
                    : 'bg-card text-card-foreground hover:bg-muted hover:shadow-md border-2 border-border'
                }`}
              >
                <Icon className="w-5 h-5 flex-shrink-0" />
                <span className="text-sm sm:text-base whitespace-nowrap">{tab.label}</span>
                {tab.badge !== undefined && (
                  <span className={`ml-1 px-2 py-0.5 rounded-full text-xs font-bold ${
                    activeTab === tab.id 
                      ? 'bg-primary-foreground text-primary' 
                      : 'bg-primary/15 text-primary'
                  }`}>
                    {tab.badge}
                  </span>
                )}
              </button>
            );
          })}
        </div>

        {/* Dashboard */}
        {activeTab === 'dashboard' && (
          <div className="space-y-6">
            <DashboardStats applications={applications} />
            <IntelligentTools onImportEmail={() => setIsEmailImportOpen(true)} />
            
            <div className="grid lg:grid-cols-3 gap-8">
              <div className="lg:col-span-2 space-y-6">
                {/* Search */}
                <div className="relative">
                  <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
                  <Input
                    placeholder="Rechercher une entreprise, poste ou lieu..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="pl-12 text-base"
                  />
                </div>

                {/* Applications list */}
                <ApplicationList
                  applications={sortedApplications}
                  searchQuery={searchQuery}
                  onEdit={handleEdit}
                  onDelete={handleDelete}
                  onGenerateCV={handleGenerateCV}
                  onGenerateLetter={handleGenerateLetter}
                  onUpdate={handleUpdateApplication}
                  onNewApplication={handleNewApplication}
                />
              </div>

              {/* Sidebar */}
              <div className="lg:col-span-1">
                <CoachingPanel tips={COACHING_LIBRARY} />
              </div>
            </div>
          </div>
        )}

        {/* Offres disponibles */}
        {activeTab === 'offres' && (
          <div className="space-y-6">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
              <div>
                <h2 className="text-2xl sm:text-3xl font-bold mb-1">Offres disponibles</h2>
                <p className="text-sm sm:text-base text-muted-foreground">Annonces importées et offres à traiter</p>
              </div>
              <Button onClick={() => setIsEmailImportOpen(true)} variant="outline" size="lg" className="gap-2 w-full sm:w-auto">
                <Plus className="w-4 h-4" />
                Importer des offres
              </Button>
            </div>

            {/* Search and Filters */}
            <div className="flex flex-col sm:flex-row gap-3">
              <div className="relative flex-1">
                <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
                <Input
                  placeholder="Rechercher une offre..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-12"
                />
              </div>
              <FilterPanel
                filters={filters}
                onFilterChange={setFilters}
                onReset={() => setFilters({})}
              />
            </div>

            {/* Offres list */}
            {sortedFilteredOffres.length === 0 ? (
              <div className="text-center py-16 sm:py-20 px-4">
                <div className="w-16 h-16 sm:w-20 sm:h-20 bg-muted rounded-full flex items-center justify-center mx-auto mb-4 shadow-sm">
                  <Target className="w-8 h-8 sm:w-10 sm:h-10 text-muted-foreground" />
                </div>
                <h3 className="text-lg sm:text-xl font-semibold mb-2">Aucune offre</h3>
                <p className="text-sm sm:text-base text-muted-foreground mb-6 max-w-md mx-auto leading-relaxed">
                  {searchQuery ? 'Aucun résultat trouvé' : 'Importez des offres d\'emploi pour commencer'}
                </p>
                {!searchQuery && (
                  <Button onClick={() => setIsEmailImportOpen(true)} size="lg">
                    <Plus className="w-4 h-4 mr-2" />
                    Importer des offres
                  </Button>
                )}
              </div>
            ) : (
              <div className="space-y-4 sm:space-y-5">
                {sortedFilteredOffres.map((application) => (
                  <ApplicationCard
                    key={application.id}
                    application={application}
                    onEdit={() => handleEdit(application)}
                    onDelete={() => handleDelete(application.id)}
                    onGenerateCV={() => handleGenerateCV(application)}
                    onGenerateLetter={() => handleGenerateLetter(application)}
                    onUpdate={(updates) => handleUpdateApplication(application.id, updates)}
                  />
                ))}
              </div>
            )}
          </div>
        )}

        {/* Mes candidatures - En cours de travail */}
        {activeTab === 'candidatures' && (
          <div className="space-y-6">
            <div className="mb-6">
              <h2 className="text-2xl sm:text-3xl font-bold mb-1">En cours de travail</h2>
              <p className="text-sm sm:text-base text-muted-foreground">Dossiers en préparation (pas encore envoyés)</p>
            </div>

            {/* Search and Filters */}
            <div className="flex flex-col sm:flex-row gap-3">
              <div className="relative flex-1">
                <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
                <Input
                  placeholder="Rechercher..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-12"
                />
              </div>
              <FilterPanel
                filters={filters}
                onFilterChange={setFilters}
                onReset={() => setFilters({})}
              />
            </div>

            {/* Candidatures list */}
            {sortedFilteredCandidatures.length === 0 ? (
              <div className="text-center py-16">
                <div className="w-16 h-16 bg-muted rounded-full flex items-center justify-center mx-auto mb-4">
                  <Briefcase className="w-8 h-8 text-muted-foreground" />
                </div>
                <h3 className="text-lg font-semibold mb-2">Aucun dossier en cours</h3>
                <p className="text-muted-foreground mb-4">
                  {searchQuery ? 'Aucun résultat trouvé' : 'Passez une offre au statut "en cours" pour la voir ici'}
                </p>
              </div>
            ) : (
              <div className="space-y-4">
                {sortedFilteredCandidatures.map((application) => (
                  <ApplicationCard
                    key={application.id}
                    application={application}
                    onEdit={() => handleEdit(application)}
                    onDelete={() => handleDelete(application.id)}
                    onGenerateCV={() => handleGenerateCV(application)}
                    onGenerateLetter={() => handleGenerateLetter(application)}
                    onUpdate={(updates) => handleUpdateApplication(application.id, updates)}
                  />
                ))}
              </div>
            )}
          </div>
        )}

        {/* Archives - Expirées et Envoyées */}
        {activeTab === 'archives' && (
          <div className="space-y-6">
            <div className="mb-6">
              <h2 className="text-2xl sm:text-3xl font-bold mb-1">Archives / Historique</h2>
              <p className="text-sm sm:text-base text-muted-foreground">Offres expirées et candidatures envoyées</p>
            </div>

            {/* Search */}
            <div className="flex flex-col sm:flex-row gap-3">
              <div className="relative flex-1">
                <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
                <Input
                  placeholder="Rechercher dans les archives..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-12"
                />
              </div>
            </div>

            {/* Archives list */}
            {sortedFilteredArchives.length === 0 ? (
              <div className="text-center py-16">
                <div className="w-16 h-16 bg-muted rounded-full flex items-center justify-center mx-auto mb-4">
                  <Database className="w-8 h-8 text-muted-foreground" />
                </div>
                <h3 className="text-lg font-semibold mb-2">Archives vides</h3>
                <p className="text-muted-foreground mb-4">
                  {searchQuery ? 'Aucun résultat trouvé' : 'Les offres expirées et candidatures envoyées apparaîtront ici'}
                </p>
              </div>
            ) : (
              <div className="space-y-4">
                {sortedFilteredArchives.map((application) => (
                  <ApplicationCard
                    key={application.id}
                    application={application}
                    onEdit={() => handleEdit(application)}
                    onDelete={() => handleDelete(application.id)}
                    onGenerateCV={() => handleGenerateCV(application)}
                    onGenerateLetter={() => handleGenerateLetter(application)}
                    onUpdate={(updates) => handleUpdateApplication(application.id, updates)}
                    isArchived
                  />
                ))}
              </div>
            )}
          </div>
        )}

        {/* Calendrier - Vue Semaine */}
        {activeTab === 'calendrier' && (
          <WeekCalendarView applications={applications} tasks={personalTasks} />
        )}

        {/* Tâches Personnelles */}
        {activeTab === 'taches' && (
          <PersonalTaskManager 
            tasks={personalTasks}
            onAddTask={addPersonalTask}
            onToggleTask={togglePersonalTask}
            onDeleteTask={deletePersonalTask}
            onUpdateTask={updatePersonalTask}
          />
        )}

        {/* Productivité */}
        {activeTab === 'productivite' && (
          <ProductivityView />
        )}
      </main>

      {/* Modals */}
      <ApplicationForm
        application={editingApplication}
        open={isFormOpen}
        onClose={() => {
          setIsFormOpen(false);
          setEditingApplication(undefined);
        }}
        onSave={handleSave}
        isNewOffer={!editingApplication}
      />

      <SmartImportModal
        open={isEmailImportOpen}
        onClose={() => setIsEmailImportOpen(false)}
        onImport={handleImportJobs}
      />

      {selectedApplicationForCV && (
        <CVGeneratorModal
          candidature={selectedApplicationForCV}
          open={true}
          onClose={() => setSelectedApplicationForCV(null)}
          onSave={handleSaveCV}
        />
      )}

      {selectedApplicationForLetter && (
        <LetterGeneratorModal
          candidature={selectedApplicationForLetter}
          open={true}
          onClose={() => setSelectedApplicationForLetter(null)}
          onSave={handleSaveLetter}
        />
      )}

      <DataManager
        applications={applications}
        onImport={handleImportData}
        open={isDataManagerOpen}
        onClose={() => setIsDataManagerOpen(false)}
      />
      {/* Auto-save indicator */}
      {formattedLastSave && (
        <div className="fixed bottom-4 right-4 bg-muted/90 backdrop-blur-sm text-muted-foreground text-xs px-3 py-1.5 rounded-full shadow-sm border">
          💾 Dernière sauvegarde : {formattedLastSave}
        </div>
      )}
    </div>
  );
};

export default Index;
